# -*- coding: utf-8 -*-
"""Test12102021.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y301YQHcO6elKe3rT5t8NWee3vZb_m_d
"""

print('Hello, world!')

age = int(input('Skolko vam let?'))
print(age)

"""My program"""